---
exclude:
  - "LICENSE"
  # Generated files.
  - "**/CMakeLists.txt"
  - "linux/**/*.cc"
  - "linux/**/*.h"
  - "tools/include/**/*.h"
  - "web/flutter_bootstrap.js"
  - "windows/**/*.cc"
  - "windows/**/*.cpp"
  - "windows/**/*.h"

restylers:
  - name: dart-format
    image: "public.ecr.aws/restyled-io/restyler-dart-format:v2.3"
  - name: "*"
