# https://dart.dev/guides/language/analysis-options
# https://dart-lang.github.io/linter/lints/index.html.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true

analyzer:
  exclude:
    - '**/*.g.dart'
