version: "0.2"
dictionaryDefinitions: []
dictionaries: []
ignoreWords: []
flagWords: []
import: []
ignorePaths:
  - .github/**
  - build/**
  - LICENSE*
  - "*.json"
words:
  - armeabi
  - blocksize
  - btox
  - dylib
  - emscripten
  - ffigen
  - iphydf
  - kannywood
  - libtoxcore
  - malloc
  - messagepack
  - msgpack
  - nospam
  - randombytes
  - robinlinden
  - skwasm
  - sqlcipher
  - toxav
  - toxcore
  - toxencryptsave
  - unpad
  - yanciman
