[build]
  command = "if cd flutter; then git fetch && git reset --hard 3.24.4 && cd ..; else git clone https://github.com/flutter/flutter.git --branch 3.24.4; fi && export PATH=flutter/bin:$PATH && flutter config --enable-web && ./tools/prepare-web && flutter build web --release"
