#!/bin/sh

set -eux

./tools/prepare

# SQLite wasm/js.
SQLITE_VERSION=0.5.26
curl -L "https://github.com/simolus3/sqlite3.dart/releases/download/sqlite3_flutter_libs-$SQLITE_VERSION/sqlite3.wasm" >web/sqlite3.wasm

# Drift worker.
DRIFT_VERSION=2.21.0
curl -L "https://github.com/simolus3/drift/releases/download/drift-$DRIFT_VERSION/drift_worker.js" >web/drift_worker.js
