#!/usr/bin/env bash

set -eux

if [ ! -e tools/include/tox/tox.h ]; then
  # Headers are currently from the Linux build.
  tar --strip-components=2 -C tools/include/ \
    -zxf <(curl -L https://github.com/TokTok/c-toxcore/releases/download/nightly/toxcore-nightly-linux-x86_64.tar.gz) \
    toxcore-linux-x86_64/include/
fi

# We don't have Windows DLLs yet.
if [ "${RUNNER_OS:-}" = "Windows" ]; then
  exit 0
fi

# Linux
if [ ! -e linux/vendored/libtoxcore.so ]; then
  tar --strip-components=2 -C linux/vendored/ \
    -zxf <(curl -L https://github.com/TokTok/c-toxcore/releases/download/nightly/toxcore-nightly-linux-x86_64.tar.gz) \
    toxcore-linux-x86_64/lib/
fi

# macOS and iOS
if [ ! -d ios/Tox.xcframework ]; then
  tar -C ios/ \
    -zxf <(curl -L https://github.com/TokTok/c-toxcore/releases/download/nightly/toxcore-nightly-xcframework.tar.gz)
fi
if [ ! -d macos/Tox.xcframework ]; then
  cp -r ios/Tox.xcframework macos/
fi

# Android
for arch in armeabi-v7a arm64-v8a x86 x86_64; do
  if [ ! -e "android/app/src/main/jniLibs/$arch/libtoxcore.so" ]; then
    mkdir -p "android/app/src/main/jniLibs/$arch"
    tar --strip-components=2 -C "android/app/src/main/jniLibs/$arch/" \
      -zxf <(curl -L "https://github.com/TokTok/c-toxcore/releases/download/nightly/toxcore-nightly-android-$arch.tar.gz") \
      "toxcore-android-$arch/lib/libtoxcore.so"
  fi
done
