#!/usr/bin/env bash

set -eux -o pipefail

# SQLite wasm/js.
SQLITE_VERSION=2.6.1
curl -L "https://github.com/simolus3/sqlite3.dart/releases/download/sqlite3-$SQLITE_VERSION/sqlite3.wasm" -o web/sqlite3.wasm

# Drift worker.
DRIFT_VERSION=2.23.1
curl -L "https://github.com/simolus3/drift/releases/download/drift-$DRIFT_VERSION/drift_worker.js" -o web/drift_worker.js

# Sodium libs.
flutter pub run sodium_libs:update_web

# Toxcore libs.
tar -C web/ -zxf <(curl -L https://github.com/TokTok/c-toxcore/releases/download/nightly/toxcore-nightly-wasm.tar.gz)

tools/prepare
