#!/usr/bin/env bash

set -eux -o pipefail

# SQLite wasm/js.
SQLITE_VERSION=2.9.4
curl -L "https://github.com/simolus3/sqlite3.dart/releases/download/sqlite3-$SQLITE_VERSION/sqlite3.wasm" -o web/sqlite3.wasm

# Drift worker.
DRIFT_VERSION=2.31.0
curl -L "https://github.com/simolus3/drift/releases/download/drift-$DRIFT_VERSION/drift_worker.js" -o web/drift_worker.js

# Sodium libs.
LIBSODIUM_JS_VERSION=0.7.14
curl -L "https://raw.githubusercontent.com/jedisct1/libsodium.js/$LIBSODIUM_JS_VERSION/dist/browsers/sodium.js" -o web/sodium.js

# Toxcore libs.
tar -C web/ -zxf <(curl -L https://github.com/TokTok/c-toxcore/releases/download/nightly/toxcore-nightly-wasm.tar.gz)

tools/prepare
