#!/bin/sh

set -eux

if [ -d ../c-toxcore ]; then
  docker build -t toxchat/toxcore-js -f ../c-toxcore/other/emscripten/Dockerfile ../c-toxcore
fi
docker build -t registry.heroku.com/tox/web -f Dockerfile .
docker run --rm -it -p 28192:8080 --env PORT=8080 registry.heroku.com/tox/web
