name: ci

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]

# Cancel old PR builds when pushing new commits.
concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_CHANNEL: "stable"
  FLUTTER_VERSION: "3.29.0"

jobs:
  common:
    uses: TokTok/ci-tools/.github/workflows/common-ci.yml@master

  prepare:
    name: Prepare
    uses: TokTok/ci-tools/.github/workflows/deploy-prepare.yml@master

  format:
    if: github.event_name != 'push'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          # Formatter changed in 3.29. We're not ready yet.
          flutter-version: "3.27.4"
          cache: true
      - run: dart format . && git diff --exit-code

  analyze:
    if: github.event_name != 'push'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - run: ./tools/prepare
      - run: flutter analyze .

  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - run: sudo apt-get install -y libsqlite3-dev
      - run: ./tools/prepare
      - run: flutter test --coverage
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
      - name: Upload failed test goldens
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-test-goldens
          path: test/failures

  android-build:
    needs: [prepare]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - run: ./tools/prepare
      - run: flutter build apk
      - run: cp build/app/outputs/flutter-apk/app-release.apk btox-android.apk
      - uses: actions/upload-artifact@v4
        with:
          name: btox-android.apk
          path: btox-android.apk
      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          artifacts: btox-android.apk

  linux-build:
    needs: [prepare]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - run: sudo apt-get update && sudo apt-get install -y --no-install-recommends ninja-build libgtk-3-dev
      - run: ./tools/prepare
      - run: flutter build linux
      - run: tar zcf btox-linux.tar.gz -C build/linux/x64/release bundle
      - uses: actions/upload-artifact@v4
        with:
          name: btox-linux.tar.gz
          path: btox-linux.tar.gz
      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          artifacts: btox-linux.tar.gz

  ios-build:
    needs: [prepare]
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - run: ./tools/prepare
      - run: flutter build ios --no-codesign
      - run: |
          mkdir Payload
          mv build/ios/iphoneos/Runner.app Payload
          zip -r btox-ios.zip Payload
          mv btox-ios.zip btox-ios.ipa
      - uses: actions/upload-artifact@v4
        with:
          name: btox-ios.ipa
          path: btox-ios.ipa
      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          artifacts: btox-ios.ipa

  macos-build:
    needs: [prepare]
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - run: ./tools/prepare
      - run: flutter build macos
      - run: tar zcf btox-macos.tar.gz -C build/macos/Build/Products/Release btox.app
      - uses: actions/upload-artifact@v4
        with:
          name: btox-macos.tar.gz
          path: btox-macos.tar.gz
      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          artifacts: btox-macos.tar.gz

  windows-build:
    needs: [prepare]
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - run: ./tools/prepare
      - run: flutter build windows
      - run: cp build/windows/x64/runner/Release/btox.exe btox-windows-x64.exe
      - uses: actions/upload-artifact@v4
        with:
          name: btox-windows-x64.exe
          path: btox-windows-x64.exe
      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          artifacts: btox-windows-x64.exe
